version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: makanmen-app
    container_name: makanmen-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - makanmen-network

  web:
    image: nginx:alpine
    container_name: makanmen-web
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - makanmen-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: makanmen-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-makanmen}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-makanmen_user}
    ports:
      - "3313:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - makanmen-network

networks:
  makanmen-network:
    driver: bridge

volumes:
  db-data:
